<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Capa_Entidad\Capa_Entidad.csproj" />
    <ProjectReference Include="..\Capa_Logica\Capa_Logica.csproj" />
    <ProjectReference Include="..\Capa_de_datos\Capa_de_datos.csproj" />
  </ItemGroup>

</Project>